package corbas;

/**
* corba/AccountManagementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:02:00 PM EAT
*/


// Interface for Account Management
public final class AccountManagementHolder implements org.omg.CORBA.portable.Streamable
{
  public corbas.AccountManagement value = null;

  public AccountManagementHolder ()
  {
  }

  public AccountManagementHolder (corbas.AccountManagement initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbas.AccountManagementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbas.AccountManagementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbas.AccountManagementHelper.type ();
  }

}
