package corbas;

/**
* corba/AccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:02:00 PM EAT
*/

public final class AccountHolder implements org.omg.CORBA.portable.Streamable
{
  public corbas.Account value = null;

  public AccountHolder ()
  {
  }

  public AccountHolder (corbas.Account initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbas.AccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbas.AccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbas.AccountHelper.type ();
  }

}
