package corbas;


/**
* corba/AccountManagementPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:02:00 PM EAT
*/


// Interface for Account Management
public abstract class AccountManagementPOA extends org.omg.PortableServer.Servant
 implements corbas.AccountManagementOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createAccount", new java.lang.Integer (0));
    _methods.put ("getAccount", new java.lang.Integer (1));
    _methods.put ("getAllAccounts", new java.lang.Integer (2));
    _methods.put ("searchAccounts", new java.lang.Integer (3));
    _methods.put ("updateAccount", new java.lang.Integer (4));
    _methods.put ("deleteAccount", new java.lang.Integer (5));
    _methods.put ("deposit", new java.lang.Integer (6));
    _methods.put ("withdraw", new java.lang.Integer (7));
    _methods.put ("checkBalance", new java.lang.Integer (8));
    _methods.put ("getAccountTransactions", new java.lang.Integer (9));
    _methods.put ("transferFunds", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/AccountManagement/createAccount
       {
         corbas.Account account = corbas.AccountHelper.read (in);
         this.createAccount (account);
         out = $rh.createReply();
         break;
       }

       case 1:  // corba/AccountManagement/getAccount
       {
         try {
           int accId = in.read_long ();
           corbas.Account $result = null;
           $result = this.getAccount (accId);
           out = $rh.createReply();
           corbas.AccountHelper.write (out, $result);
         } catch (corbas.AccountNotFound $ex) {
           out = $rh.createExceptionReply ();
           corbas.AccountNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // corba/AccountManagement/getAllAccounts
       {
         corbas.Account $result[] = null;
         $result = this.getAllAccounts ();
         out = $rh.createReply();
         corbas.AccountListHelper.write (out, $result);
         break;
       }

       case 3:  // corba/AccountManagement/searchAccounts
       {
         String query = in.read_string ();
         corbas.Account $result[] = null;
         $result = this.searchAccounts (query);
         out = $rh.createReply();
         corbas.AccountListHelper.write (out, $result);
         break;
       }

       case 4:  // corba/AccountManagement/updateAccount
       {
         try {
           corbas.Account account = corbas.AccountHelper.read (in);
           this.updateAccount (account);
           out = $rh.createReply();
         } catch (corbas.AccountNotFound $ex) {
           out = $rh.createExceptionReply ();
           corbas.AccountNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // corba/AccountManagement/deleteAccount
       {
         try {
           int accId = in.read_long ();
           this.deleteAccount (accId);
           out = $rh.createReply();
         } catch (corbas.AccountNotFound $ex) {
           out = $rh.createExceptionReply ();
           corbas.AccountNotFoundHelper.write (out, $ex);
         }
         break;
       }


  // New functionalities for banking
       case 6:  // corba/AccountManagement/deposit
       {
         try {
           int accId = in.read_long ();
           double amount = in.read_double ();
           double $result = (double)0;
           $result = this.deposit (accId, amount);
           out = $rh.createReply();
           out.write_double ($result);
         } catch (corbas.AccountNotFound $ex) {
           out = $rh.createExceptionReply ();
           corbas.AccountNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 7:  // corba/AccountManagement/withdraw
       {
         try {
           int accId = in.read_long ();
           double amount = in.read_double ();
           double $result = (double)0;
           $result = this.withdraw (accId, amount);
           out = $rh.createReply();
           out.write_double ($result);
         } catch (corbas.AccountNotFound $ex) {
           out = $rh.createExceptionReply ();
           corbas.AccountNotFoundHelper.write (out, $ex);
         } catch (corbas.InsufficientFunds $ex) {
           out = $rh.createExceptionReply ();
           corbas.InsufficientFundsHelper.write (out, $ex);
         }
         break;
       }

       case 8:  // corba/AccountManagement/checkBalance
       {
         try {
           int accId = in.read_long ();
           double $result = (double)0;
           $result = this.checkBalance (accId);
           out = $rh.createReply();
           out.write_double ($result);
         } catch (corbas.AccountNotFound $ex) {
           out = $rh.createExceptionReply ();
           corbas.AccountNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 9:  // corba/AccountManagement/getAccountTransactions
       {
         try {
           int accId = in.read_long ();
           corbas.Transaction $result[] = null;
           $result = this.getAccountTransactions (accId);
           out = $rh.createReply();
           corbas.TransactionListHelper.write (out, $result);
         } catch (corbas.AccountNotFound $ex) {
           out = $rh.createExceptionReply ();
           corbas.AccountNotFoundHelper.write (out, $ex);
         }
         break;
       }


  // Fund transfer between accounts
       case 10:  // corba/AccountManagement/transferFunds
       {
         try {
           int fromAccId = in.read_long ();
           int toAccId = in.read_long ();
           double amount = in.read_double ();
           this.transferFunds (fromAccId, toAccId, amount);
           out = $rh.createReply();
         } catch (corbas.AccountNotFound $ex) {
           out = $rh.createExceptionReply ();
           corbas.AccountNotFoundHelper.write (out, $ex);
         } catch (corbas.InsufficientFunds $ex) {
           out = $rh.createExceptionReply ();
           corbas.InsufficientFundsHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/AccountManagement:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AccountManagement _this() 
  {
    return AccountManagementHelper.narrow(
    super._this_object());
  }

  public AccountManagement _this(org.omg.CORBA.ORB orb) 
  {
    return AccountManagementHelper.narrow(
    super._this_object(orb));
  }


} // class AccountManagementPOA
