package corbas;

/**
* corba/AccountNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:02:00 PM EAT
*/

public final class AccountNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public corbas.AccountNotFound value = null;

  public AccountNotFoundHolder ()
  {
  }

  public AccountNotFoundHolder (corbas.AccountNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbas.AccountNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbas.AccountNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbas.AccountNotFoundHelper.type ();
  }

}
