package corbas;


/**
* corba/InsufficientFunds.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:02:00 PM EAT
*/

public final class InsufficientFunds extends org.omg.CORBA.UserException
{
  public double currentBalance = (double)0;

  public InsufficientFunds ()
  {
    super(InsufficientFundsHelper.id());
  } // ctor

  public InsufficientFunds (double _currentBalance)
  {
    super(InsufficientFundsHelper.id());
    currentBalance = _currentBalance;
  } // ctor


  public InsufficientFunds (String $reason, double _currentBalance)
  {
    super(InsufficientFundsHelper.id() + "  " + $reason);
    currentBalance = _currentBalance;
  } // ctor

} // class InsufficientFunds
