package corbas;

/**
* corba/InsufficientFundsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:02:00 PM EAT
*/

public final class InsufficientFundsHolder implements org.omg.CORBA.portable.Streamable
{
  public corbas.InsufficientFunds value = null;

  public InsufficientFundsHolder ()
  {
  }

  public InsufficientFundsHolder (corbas.InsufficientFunds initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbas.InsufficientFundsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbas.InsufficientFundsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbas.InsufficientFundsHelper.type ();
  }

}
