package corbas;

/**
* corba/TransactionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:02:00 PM EAT
*/

public final class TransactionHolder implements org.omg.CORBA.portable.Streamable
{
  public corbas.Transaction value = null;

  public TransactionHolder ()
  {
  }

  public TransactionHolder (corbas.Transaction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbas.TransactionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbas.TransactionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbas.TransactionHelper.type ();
  }

}
