package corbas;


/**
* corba/Transaction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:02:00 PM EAT
*/

public final class Transaction implements org.omg.CORBA.portable.IDLEntity
{
  public int transactionId = (int)0;
  public int accId = (int)0;
  public double amount = (double)0;
  public String transactionType = null;

  // "deposit" or "withdrawal"
  public String date = null;

  public Transaction ()
  {
  } // ctor

  public Transaction (int _transactionId, int _accId, double _amount, String _transactionType, String _date)
  {
    transactionId = _transactionId;
    accId = _accId;
    amount = _amount;
    transactionType = _transactionType;
    date = _date;
  } // ctor

} // class Transaction
