package corbas;

/**
* corba/UnauthorizedAccessHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:02:00 PM EAT
*/

public final class UnauthorizedAccessHolder implements org.omg.CORBA.portable.Streamable
{
  public corbas.UnauthorizedAccess value = null;

  public UnauthorizedAccessHolder ()
  {
  }

  public UnauthorizedAccessHolder (corbas.UnauthorizedAccess initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbas.UnauthorizedAccessHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbas.UnauthorizedAccessHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbas.UnauthorizedAccessHelper.type ();
  }

}
