package corbas;


/**
* corba/UserManagementOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:02:00 PM EAT
*/


// Interface for User Management
public interface UserManagementOperations 
{
  void createUser (corbas.User user);
  corbas.User getUser (int userId) throws corbas.UserNotFound;
  corbas.User[] getAllUsers ();
  corbas.User[] searchUsers (String query);
  void updateUser (corbas.User user) throws corbas.UserNotFound;
  void deleteUser (int userId) throws corbas.UserNotFound;
  void activateUser (int userId) throws corbas.UserNotFound;
  void deactivateUser (int userId) throws corbas.UserNotFound;
} // interface UserManagementOperations
