package corbas;

/**
* corba/UserManagementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:02:00 PM EAT
*/


// Interface for User Management
public final class UserManagementHolder implements org.omg.CORBA.portable.Streamable
{
  public corbas.UserManagement value = null;

  public UserManagementHolder ()
  {
  }

  public UserManagementHolder (corbas.UserManagement initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbas.UserManagementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbas.UserManagementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbas.UserManagementHelper.type ();
  }

}
