package corbas;

/**
* corba/UserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:02:00 PM EAT
*/

public final class UserHolder implements org.omg.CORBA.portable.Streamable
{
  public corbas.User value = null;

  public UserHolder ()
  {
  }

  public UserHolder (corbas.User initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbas.UserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbas.UserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbas.UserHelper.type ();
  }

}
