package corba;


/**
* corba/AccountManagementOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:21:01 PM EAT
*/


// Interface for managing accounts in the banking system
public interface AccountManagementOperations 
{
  void createAccount (corba.Account account);

  // Create a new account
  corba.Account getAccount (int accId);

  // Retrieve an account by its ID
  corba.Account[] getAllAccounts ();

  // Get a list of all accounts
  corba.Account[] searchAccounts (String query);

  // Search accounts based on a query
  void updateAccount (corba.Account account);

  // Update an existing account's information
  void deleteAccount (int accId);
} // interface AccountManagementOperations
