package corba;

/**
* corba/AccountManagementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:21:01 PM EAT
*/


// Interface for managing accounts in the banking system
public final class AccountManagementHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.AccountManagement value = null;

  public AccountManagementHolder ()
  {
  }

  public AccountManagementHolder (corba.AccountManagement initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.AccountManagementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.AccountManagementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.AccountManagementHelper.type ();
  }

}
