package corba;

/**
* corba/UserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:21:01 PM EAT
*/

public final class UserHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.User value = null;

  public UserHolder ()
  {
  }

  public UserHolder (corba.User initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.UserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.UserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.UserHelper.type ();
  }

}
