package corba;


/**
* corba/UserManagementOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:21:01 PM EAT
*/


// Interface for managing users in the banking system
public interface UserManagementOperations 
{
  void createUser (corba.User user);

  // Create a new user
  corba.User getUser (int userId);

  // Retrieve a user by their ID
  corba.User[] getAllUsers ();

  // Get a list of all users
  corba.User[] searchUsers (String query);

  // Search users based on a query
  void updateUser (corba.User user);

  // Update an existing user's information
  void deleteUser (int userId);

  // Delete a user by their ID
  void deactivateUser (int userId);
} // interface UserManagementOperations
