package corba;


/**
* corba/UserManagementPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlf.idl
* Monday, October 28, 2024 1:21:01 PM EAT
*/


// Interface for managing users in the banking system
public abstract class UserManagementPOA extends org.omg.PortableServer.Servant
 implements corba.UserManagementOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createUser", new java.lang.Integer (0));
    _methods.put ("getUser", new java.lang.Integer (1));
    _methods.put ("getAllUsers", new java.lang.Integer (2));
    _methods.put ("searchUsers", new java.lang.Integer (3));
    _methods.put ("updateUser", new java.lang.Integer (4));
    _methods.put ("deleteUser", new java.lang.Integer (5));
    _methods.put ("deactivateUser", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/UserManagement/createUser
       {
         corba.User user = corba.UserHelper.read (in);
         this.createUser (user);
         out = $rh.createReply();
         break;
       }


  // Create a new user
       case 1:  // corba/UserManagement/getUser
       {
         int userId = in.read_long ();
         corba.User $result = null;
         $result = this.getUser (userId);
         out = $rh.createReply();
         corba.UserHelper.write (out, $result);
         break;
       }


  // Retrieve a user by their ID
       case 2:  // corba/UserManagement/getAllUsers
       {
         corba.User $result[] = null;
         $result = this.getAllUsers ();
         out = $rh.createReply();
         corba.UserListHelper.write (out, $result);
         break;
       }


  // Get a list of all users
       case 3:  // corba/UserManagement/searchUsers
       {
         String query = in.read_string ();
         corba.User $result[] = null;
         $result = this.searchUsers (query);
         out = $rh.createReply();
         corba.UserListHelper.write (out, $result);
         break;
       }


  // Search users based on a query
       case 4:  // corba/UserManagement/updateUser
       {
         corba.User user = corba.UserHelper.read (in);
         this.updateUser (user);
         out = $rh.createReply();
         break;
       }


  // Update an existing user's information
       case 5:  // corba/UserManagement/deleteUser
       {
         int userId = in.read_long ();
         this.deleteUser (userId);
         out = $rh.createReply();
         break;
       }


  // Delete a user by their ID
       case 6:  // corba/UserManagement/deactivateUser
       {
         int userId = in.read_long ();
         this.deactivateUser (userId);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/UserManagement:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public UserManagement _this() 
  {
    return UserManagementHelper.narrow(
    super._this_object());
  }

  public UserManagement _this(org.omg.CORBA.ORB orb) 
  {
    return UserManagementHelper.narrow(
    super._this_object(orb));
  }


} // class UserManagementPOA
