package PowerApp;


/**
* PowerApp/PowerCalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Friday, October 25, 2024 9:31:15 AM EAT
*/

public interface PowerCalculatorOperations 
{
  float power (float base, float exponent);
} // interface PowerCalculatorOperations
