package PowerApp;


/**
* PowerApp/PowerCalculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Friday, October 25, 2024 9:31:15 AM EAT
*/

public interface PowerCalculator extends PowerCalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PowerCalculator
