package PowerApp;


/**
* PowerApp/PowerCalculatorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Friday, October 25, 2024 9:31:15 AM EAT
*/

public abstract class PowerCalculatorPOA extends org.omg.PortableServer.Servant
 implements PowerApp.PowerCalculatorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("power", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PowerApp/PowerCalculator/power
       {
         float base = in.read_float ();
         float exponent = in.read_float ();
         float $result = (float)0;
         $result = this.power (base, exponent);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PowerApp/PowerCalculator:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PowerCalculator _this() 
  {
    return PowerCalculatorHelper.narrow(
    super._this_object());
  }

  public PowerCalculator _this(org.omg.CORBA.ORB orb) 
  {
    return PowerCalculatorHelper.narrow(
    super._this_object(orb));
  }


} // class PowerCalculatorPOA
