package PowerApp;

/**
* PowerApp/PowerCalculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Friday, October 25, 2024 9:31:15 AM EAT
*/

public final class PowerCalculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public PowerApp.PowerCalculator value = null;

  public PowerCalculatorHolder ()
  {
  }

  public PowerCalculatorHolder (PowerApp.PowerCalculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PowerApp.PowerCalculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PowerApp.PowerCalculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PowerApp.PowerCalculatorHelper.type ();
  }

}
