package corban;

/**
* corban/AccountManagementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlnew.idl
* Monday, October 28, 2024 2:54:47 PM EAT
*/


// Interface for Account Management
public final class AccountManagementHolder implements org.omg.CORBA.portable.Streamable
{
  public corban.AccountManagement value = null;

  public AccountManagementHolder ()
  {
  }

  public AccountManagementHolder (corban.AccountManagement initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corban.AccountManagementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corban.AccountManagementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corban.AccountManagementHelper.type ();
  }

}
