package corban;

/**
* corban/AccountNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlnew.idl
* Monday, October 28, 2024 2:54:47 PM EAT
*/

public final class AccountNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public corban.AccountNotFound value = null;

  public AccountNotFoundHolder ()
  {
  }

  public AccountNotFoundHolder (corban.AccountNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corban.AccountNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corban.AccountNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corban.AccountNotFoundHelper.type ();
  }

}
