package corban;


/**
* corban/AccountManagementOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlnew.idl
* Monday, October 28, 2024 2:54:47 PM EAT
*/


// Interface for Account Management
public interface AccountManagementOperations 
{
  void createAccount (corban.Account account);
  corban.Account getAccount (int accId) throws corban.AccountNotFound;
  corban.Account[] getAllAccounts ();
  corban.Account[] searchAccounts (String query);
  void updateAccount (corban.Account account) throws corban.AccountNotFound;
  void deleteAccount (int accId) throws corban.AccountNotFound;

  // New functionalities for banking
  double deposit (int accId, double amount) throws corban.AccountNotFound;
  double withdraw (int accId, double amount) throws corban.AccountNotFound, corban.InsufficientFunds;
  double checkBalance (int accId) throws corban.AccountNotFound;
  corban.Transaction[] getAccountTransactions (int accId) throws corban.AccountNotFound;

  // Fund transfer between accounts
  void transferFunds (int fromAccId, int toAccId, double amount) throws corban.AccountNotFound, corban.InsufficientFunds;
} // interface AccountManagementOperations
