package corban;

/**
* corban/InsufficientFundsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlnew.idl
* Monday, October 28, 2024 2:54:47 PM EAT
*/

public final class InsufficientFundsHolder implements org.omg.CORBA.portable.Streamable
{
  public corban.InsufficientFunds value = null;

  public InsufficientFundsHolder ()
  {
  }

  public InsufficientFundsHolder (corban.InsufficientFunds initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corban.InsufficientFundsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corban.InsufficientFundsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corban.InsufficientFundsHelper.type ();
  }

}
