package corban;

/**
* corban/TransactionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlnew.idl
* Monday, October 28, 2024 2:54:47 PM EAT
*/

public final class TransactionHolder implements org.omg.CORBA.portable.Streamable
{
  public corban.Transaction value = null;

  public TransactionHolder ()
  {
  }

  public TransactionHolder (corban.Transaction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corban.TransactionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corban.TransactionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corban.TransactionHelper.type ();
  }

}
