package corban;


/**
* corban/UserNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlnew.idl
* Monday, October 28, 2024 2:54:47 PM EAT
*/

public final class UserNotFound extends org.omg.CORBA.UserException
{
  public int userId = (int)0;

  public UserNotFound ()
  {
    super(UserNotFoundHelper.id());
  } // ctor

  public UserNotFound (int _userId)
  {
    super(UserNotFoundHelper.id());
    userId = _userId;
  } // ctor


  public UserNotFound (String $reason, int _userId)
  {
    super(UserNotFoundHelper.id() + "  " + $reason);
    userId = _userId;
  } // ctor

} // class UserNotFound
