package corban;

/**
* corban/UserManagementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlnew.idl
* Monday, October 28, 2024 2:54:47 PM EAT
*/


// Interface for User Management
public final class UserManagementHolder implements org.omg.CORBA.portable.Streamable
{
  public corban.UserManagement value = null;

  public UserManagementHolder ()
  {
  }

  public UserManagementHolder (corban.UserManagement initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corban.UserManagementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corban.UserManagementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corban.UserManagementHelper.type ();
  }

}
