package corban;

/**
* corban/UserNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlnew.idl
* Monday, October 28, 2024 2:54:47 PM EAT
*/

public final class UserNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public corban.UserNotFound value = null;

  public UserNotFoundHolder ()
  {
  }

  public UserNotFoundHolder (corban.UserNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corban.UserNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corban.UserNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corban.UserNotFoundHelper.type ();
  }

}
